<!--
Codes Generated By VForm:
https://www.vform666.com
-->

<template>
    <el-dialog title="添加物品" v-model="dialogVisible" width="60%">
    <el-form :model="formData" ref="vForm" :rules="rules" label-position="left" label-width="80px"
             size="default" @submit.prevent>
        <el-form-item label="物品名称" prop="input69072" class="required">
            <el-input v-model="formData.input69072" type="text" clearable :maxlength="10"></el-input>
        </el-form-item>
        <el-form-item label="到期日期" prop="date36967" class="required">
            <el-date-picker v-model="formData.date36967" type="date" class="full-width-input" format="YYYY-MM-DD"
                            value-format="YYYY-MM-DD" clearable ></el-date-picker>
        </el-form-item>
        <el-form-item label="临期提醒" prop="select91450" class="required" >
            <el-select v-model="formData.select91450" class="full-width-input" placeholder="请选择提前提醒的天数" clearable @change="choose(formData.select91450)">
                <el-option v-for="(item, index) in select91450Options" :key="index" :label="item.label"
                           :value="item.value" :disabled="item.disabled" ></el-option>
            </el-select>
        </el-form-item>
        <el-form-item label="自定义" prop="sliderdays" v-show="sliderVisible">
            <el-slider v-model="formData.sliderdays"></el-slider>
        </el-form-item>
        <el-form-item label="物品标签" prop="radio49218" class="required">
            <el-radio-group v-model="formData.radio49218">
                <el-radio v-for="(item,index) in radio49218Options" :key="index"  :label="item.id"> {{item.type}}</el-radio>
            </el-radio-group>
        </el-form-item>
    </el-form>
    <span slot="footer" class="dialog-footer">
    <el-button @click="dialogVisible = false">取 消</el-button>
    <el-button type="primary" @click="submit()">确 定</el-button>
    </span>
    </el-dialog>
</template>

<script>
    import {
        defineComponent,
        toRefs,
        reactive,
        onMounted,
        getCurrentInstance
    }
        from 'vue'
    import emitter from "../event";
    import axios from "axios";
    import {ElMessage} from "element-plus";
    export default defineComponent({
        components: {},
        props: {},
        setup() {
            const state = reactive({
                dialogVisible : false,
                sliderVisible:false,
                formData: {
                    input69072: "",
                    date36967: "2022-05-01",
                    select91450: 2,
                    sliderdays: 0,
                    radio49218: null,
                },
                rules: {
                    input69072: [{
                        required: true,
                        message: '字段值不可为空',
                    }],
                    date36967: [{
                        required: true,
                        message: '字段值不可为空',
                    }],
                    select91450: [{
                        required: true,
                        message: '字段值不可为空',
                    }],
                    radio49218: [{
                        required: true,
                        message: '字段值不可为空',
                    }],
                },
                select91450Options: [{
                    "label": "过期前1天",
                    "value": 1
                }, {
                    "label": "过期前3天",
                    "value": 2
                }, {
                    "label": "过期前1周",
                    "value": 3
                }, {
                    "value": 4,
                    "label": "自定义天数"
                }],
                radio49218Options: [],
            })
            const submit = () => {
                state.dialogVisible = false;
                console.log(confirmdays(state.formData.select91450));
                console.log(typeof state.formData.date36967);
                axios.post("/api/createobject",{
                    'username' : sessionStorage.getItem('username'),
                    'information' : state.formData.input69072,
                    'expiration_time' : state.formData.date36967.toString(),
                    'reminder_time' : confirmdays(state.formData.select91450),
                    'type' : state.formData.radio49218
                }).then(res =>{
                    if (res.data.code == 200){
                        console.log(res.data.data);
                        ElMessage({
                            message: '新增物品成功',
                            type: 'success',
                        })
                        emitter.emit("flashlabel","");
                        emitter.emit("flashstate","");
                    }else {
                        console.log(res.data);
                        ElMessage.error("新增标签失败"+res.data.message);
                    }

                }).catch(function (error) {
                    console.log(error.message);
                });
            }
            const confirmdays = (value) =>{
                console.log(value);
                if (value===1) return 86400;
                if (value===2) return 86400*3;
                if (value===3) return 86400*5;
                if (value===4) return state.formData.sliderdays*86400;
            }
            onMounted(()=>{
                emitter.on("createobject",data=>{
                    console.log("get");
                    const objecttype = JSON.parse(sessionStorage.getItem('objecttype'));

                    state.radio49218Options = objecttype;
                    console.log(state.radio49218Options);
                    state.dialogVisible=true;
                })
            })
            const choose = (value)=>{
                state.sliderVisible = value === 4;
            }
            return {
                ...toRefs(state),
                choose,
                submit
            }
        }
    })

</script>

<style lang="scss">
    .el-input-number.full-width-input,
    .el-cascader.full-width-input {
        width: 100% !important;
    }

    .el-form-item--medium {
        .el-radio {
            line-height: 36px !important;
        }

        .el-rate {
            margin-top: 8px;
        }
    }

    .el-form-item--small {
        .el-radio {
            line-height: 32px !important;
        }

        .el-rate {
            margin-top: 6px;
        }
    }

    .el-form-item--mini {
        .el-radio {
            line-height: 28px !important;
        }

        .el-rate {
            margin-top: 4px;
        }
    }

    .clear-fix:before,
    .clear-fix:after {
        display: table;
        content: "";
    }

    .clear-fix:after {
        clear: both;
    }

    .float-right {
        float: right;
    }

</style>

<style lang="scss" scoped>
    div.table-container {
        table.table-layout {
            width: 100%;
            table-layout: fixed;
            border-collapse: collapse;

            td.table-cell {
                display: table-cell;
                height: 36px;
                border: 1px solid #e1e2e3;
            }
        }
    }

    div.tab-container {}

    .label-left-align :deep(.el-form-item__label) {
        text-align: left;
    }

    .label-center-align :deep(.el-form-item__label) {
        text-align: center;
    }

    .label-right-align :deep(.el-form-item__label) {
        text-align: right;
    }

    .custom-label {}

    .static-content-item {
        min-height: 20px;
        display: flex;
        align-items: center;

        :deep(.el-divider--horizontal) {
            margin: 0;
        }
    }

</style>