<!--
Codes Generated By VForm:
https://www.vform666.com
-->

<template>
    <el-dialog title="添加列表" v-model="dialogVisible" width="60%">
        <el-form :model="formData" ref="vForm" :rules="rules" label-position="left" label-width="80px"
                 size="default" @submit.prevent>
            <el-form-item label="标签名称" prop="input69072" class="required">
                <el-input v-model="formData.input69072" type="text" clearable :maxlength="7"></el-input>
            </el-form-item>
        </el-form>
    <span slot="footer" class="dialog-footer">
    <el-button @click="dialogVisible = false">取 消</el-button>
    <el-button type="primary" @click="submit()">确 定</el-button>
    </span>
    </el-dialog>
</template>

<script>
    import {
        defineComponent,
        toRefs,
        reactive,
        onMounted
    }
        from 'vue'
    import emitter from '../event'
    import axios from "axios";
    import {ElMessage} from "element-plus";
    export default defineComponent({
        components: {},
        props: {},
        setup() {
            const state = reactive({
                dialogVisible : false,
                formData: {
                    input69072: "",
                },
                rules: {
                    input69072: [{
                        required: true,
                        message: '字段值不可为空',
                    }],
                },
            })
            const submit = () => {
                state.dialogVisible = false;
                axios.post("/api/createobjecttype",{
                    'username' : sessionStorage.getItem('username'),
                    'type' : state.formData.input69072,
                }).then(res =>{
                    if (res.data.code == 200){
                        console.log(res.data.data);
                        ElMessage({
                            message: '新增标签成功',
                            type: 'success',
                        })
                        emitter.emit("flashlabel","")
                    }else {
                        console.log(res.data);
                        ElMessage.error("新增标签失败"+res.data.message);
                    }

                }).catch(function (error) {
                    console.log(error.message);
                });
            }

            onMounted(() => {
                emitter.on("addlabel",data=>{
                    console.log("接收到")
                    state.dialogVisible = true;
                })
            })
            return {
                ...toRefs(state),
                submit
            }
        }
    })

</script>

<style lang="scss">
    .el-input-number.full-width-input,
    .el-cascader.full-width-input {
        width: 100% !important;
    }

    .el-form-item--medium {
        .el-radio {
            line-height: 36px !important;
        }

        .el-rate {
            margin-top: 8px;
        }
    }

    .el-form-item--small {
        .el-radio {
            line-height: 32px !important;
        }

        .el-rate {
            margin-top: 6px;
        }
    }

    .el-form-item--mini {
        .el-radio {
            line-height: 28px !important;
        }

        .el-rate {
            margin-top: 4px;
        }
    }

    .clear-fix:before,
    .clear-fix:after {
        display: table;
        content: "";
    }

    .clear-fix:after {
        clear: both;
    }

    .float-right {
        float: right;
    }

</style>

<style lang="scss" scoped>
    div.table-container {
        table.table-layout {
            width: 100%;
            table-layout: fixed;
            border-collapse: collapse;

            td.table-cell {
                display: table-cell;
                height: 36px;
                border: 1px solid #e1e2e3;
            }
        }
    }

    div.tab-container {}

    .label-left-align :deep(.el-form-item__label) {
        text-align: left;
    }

    .label-center-align :deep(.el-form-item__label) {
        text-align: center;
    }

    .label-right-align :deep(.el-form-item__label) {
        text-align: right;
    }

    .custom-label {}

    .static-content-item {
        min-height: 20px;
        display: flex;
        align-items: center;

        :deep(.el-divider--horizontal) {
            margin: 0;
        }
    }

</style>